name: Test Go Hash Action on GT
on: push
jobs:
  exec:
    runs-on: host-ubuntu-20.04
    steps:
      - uses: https://github.com/actions/checkout@v3
        with:
          github-server-url: 'http://host.docker.internal:3000'

      - uses: https://gitea.com/Zettat123/go-hashfiles@main
        id: get-hash
        with: 
          patterns: |-
            go.sum
            ./modules/admin/*
            **/package-lock.json

      - name: Echo hash
        run: echo ${{ steps.get-hash.outputs.hash }}
      - name: Echo matched files
        run: echo ${{ steps.get-hash.outputs.matched-files }}
