name: Test Go Hash Action on GH
on: push
jobs:
  exec:
    runs-on: 	ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo hash
        run: echo result-is-${{ hashFiles('go.sum', 'modules/admin/README.txt') }}
